### PR TITLE
4 make calendar overview

### LINKED ISSUE #4: Make Calendar Overview
This is for overview in homepage.

### LINKED ISSUE #13: Integrate Calendar to Home

### PR DESCRIPTION
**Pull request by mystreamer**

### CODE REVIEW

**Comment by mystreamer** [comment]
The merge does not seem to cause any conflicts...

**Comment by YufXiao** [comment]
how can i access to the home page? Should there be a route redirect to that page in AppRouter? @mystreamer

**Comment by mystreamer** [comment]
@YufXiao Yes, but it is in the next branch #45 , to access it, you must either do `export REACT_APP_MIRAGE=true` before doing `npm run dev` and do a registration with fake data, or you can locally deactivate the HomeGuard, LoginGuard. The only problem currently will be that in production it does not currently, work... so now we need to integrate with the real backend.

**Comment by mystreamer** [comment]
I will add flags, so it also works non-MIRAGE.

**Pull request merged**
